// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fft_fft_stages (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        X_R_0_address0,
        X_R_0_ce0,
        X_R_0_q0,
        X_R_0_address1,
        X_R_0_ce1,
        X_R_0_q1,
        X_R_1_address0,
        X_R_1_ce0,
        X_R_1_q0,
        X_R_1_address1,
        X_R_1_ce1,
        X_R_1_q1,
        X_R_2_address0,
        X_R_2_ce0,
        X_R_2_q0,
        X_R_2_address1,
        X_R_2_ce1,
        X_R_2_q1,
        X_R_3_address0,
        X_R_3_ce0,
        X_R_3_q0,
        X_R_3_address1,
        X_R_3_ce1,
        X_R_3_q1,
        X_I_0_address0,
        X_I_0_ce0,
        X_I_0_q0,
        X_I_0_address1,
        X_I_0_ce1,
        X_I_0_q1,
        X_I_1_address0,
        X_I_1_ce0,
        X_I_1_q0,
        X_I_1_address1,
        X_I_1_ce1,
        X_I_1_q1,
        X_I_2_address0,
        X_I_2_ce0,
        X_I_2_q0,
        X_I_2_address1,
        X_I_2_ce1,
        X_I_2_q1,
        X_I_3_address0,
        X_I_3_ce0,
        X_I_3_q0,
        X_I_3_address1,
        X_I_3_ce1,
        X_I_3_q1,
        stage,
        OUT_R_0_address0,
        OUT_R_0_ce0,
        OUT_R_0_we0,
        OUT_R_0_d0,
        OUT_R_0_address1,
        OUT_R_0_ce1,
        OUT_R_0_we1,
        OUT_R_0_d1,
        OUT_R_1_address0,
        OUT_R_1_ce0,
        OUT_R_1_we0,
        OUT_R_1_d0,
        OUT_R_1_address1,
        OUT_R_1_ce1,
        OUT_R_1_we1,
        OUT_R_1_d1,
        OUT_R_2_address0,
        OUT_R_2_ce0,
        OUT_R_2_we0,
        OUT_R_2_d0,
        OUT_R_2_address1,
        OUT_R_2_ce1,
        OUT_R_2_we1,
        OUT_R_2_d1,
        OUT_R_3_address0,
        OUT_R_3_ce0,
        OUT_R_3_we0,
        OUT_R_3_d0,
        OUT_R_3_address1,
        OUT_R_3_ce1,
        OUT_R_3_we1,
        OUT_R_3_d1,
        OUT_I_0_address0,
        OUT_I_0_ce0,
        OUT_I_0_we0,
        OUT_I_0_d0,
        OUT_I_0_address1,
        OUT_I_0_ce1,
        OUT_I_0_we1,
        OUT_I_0_d1,
        OUT_I_1_address0,
        OUT_I_1_ce0,
        OUT_I_1_we0,
        OUT_I_1_d0,
        OUT_I_1_address1,
        OUT_I_1_ce1,
        OUT_I_1_we1,
        OUT_I_1_d1,
        OUT_I_2_address0,
        OUT_I_2_ce0,
        OUT_I_2_we0,
        OUT_I_2_d0,
        OUT_I_2_address1,
        OUT_I_2_ce1,
        OUT_I_2_we1,
        OUT_I_2_d1,
        OUT_I_3_address0,
        OUT_I_3_ce0,
        OUT_I_3_we0,
        OUT_I_3_d0,
        OUT_I_3_address1,
        OUT_I_3_ce1,
        OUT_I_3_we1,
        OUT_I_3_d1
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] X_R_0_address0;
output   X_R_0_ce0;
input  [31:0] X_R_0_q0;
output  [7:0] X_R_0_address1;
output   X_R_0_ce1;
input  [31:0] X_R_0_q1;
output  [7:0] X_R_1_address0;
output   X_R_1_ce0;
input  [31:0] X_R_1_q0;
output  [7:0] X_R_1_address1;
output   X_R_1_ce1;
input  [31:0] X_R_1_q1;
output  [7:0] X_R_2_address0;
output   X_R_2_ce0;
input  [31:0] X_R_2_q0;
output  [7:0] X_R_2_address1;
output   X_R_2_ce1;
input  [31:0] X_R_2_q1;
output  [7:0] X_R_3_address0;
output   X_R_3_ce0;
input  [31:0] X_R_3_q0;
output  [7:0] X_R_3_address1;
output   X_R_3_ce1;
input  [31:0] X_R_3_q1;
output  [7:0] X_I_0_address0;
output   X_I_0_ce0;
input  [31:0] X_I_0_q0;
output  [7:0] X_I_0_address1;
output   X_I_0_ce1;
input  [31:0] X_I_0_q1;
output  [7:0] X_I_1_address0;
output   X_I_1_ce0;
input  [31:0] X_I_1_q0;
output  [7:0] X_I_1_address1;
output   X_I_1_ce1;
input  [31:0] X_I_1_q1;
output  [7:0] X_I_2_address0;
output   X_I_2_ce0;
input  [31:0] X_I_2_q0;
output  [7:0] X_I_2_address1;
output   X_I_2_ce1;
input  [31:0] X_I_2_q1;
output  [7:0] X_I_3_address0;
output   X_I_3_ce0;
input  [31:0] X_I_3_q0;
output  [7:0] X_I_3_address1;
output   X_I_3_ce1;
input  [31:0] X_I_3_q1;
input  [3:0] stage;
output  [7:0] OUT_R_0_address0;
output   OUT_R_0_ce0;
output   OUT_R_0_we0;
output  [31:0] OUT_R_0_d0;
output  [7:0] OUT_R_0_address1;
output   OUT_R_0_ce1;
output   OUT_R_0_we1;
output  [31:0] OUT_R_0_d1;
output  [7:0] OUT_R_1_address0;
output   OUT_R_1_ce0;
output   OUT_R_1_we0;
output  [31:0] OUT_R_1_d0;
output  [7:0] OUT_R_1_address1;
output   OUT_R_1_ce1;
output   OUT_R_1_we1;
output  [31:0] OUT_R_1_d1;
output  [7:0] OUT_R_2_address0;
output   OUT_R_2_ce0;
output   OUT_R_2_we0;
output  [31:0] OUT_R_2_d0;
output  [7:0] OUT_R_2_address1;
output   OUT_R_2_ce1;
output   OUT_R_2_we1;
output  [31:0] OUT_R_2_d1;
output  [7:0] OUT_R_3_address0;
output   OUT_R_3_ce0;
output   OUT_R_3_we0;
output  [31:0] OUT_R_3_d0;
output  [7:0] OUT_R_3_address1;
output   OUT_R_3_ce1;
output   OUT_R_3_we1;
output  [31:0] OUT_R_3_d1;
output  [7:0] OUT_I_0_address0;
output   OUT_I_0_ce0;
output   OUT_I_0_we0;
output  [31:0] OUT_I_0_d0;
output  [7:0] OUT_I_0_address1;
output   OUT_I_0_ce1;
output   OUT_I_0_we1;
output  [31:0] OUT_I_0_d1;
output  [7:0] OUT_I_1_address0;
output   OUT_I_1_ce0;
output   OUT_I_1_we0;
output  [31:0] OUT_I_1_d0;
output  [7:0] OUT_I_1_address1;
output   OUT_I_1_ce1;
output   OUT_I_1_we1;
output  [31:0] OUT_I_1_d1;
output  [7:0] OUT_I_2_address0;
output   OUT_I_2_ce0;
output   OUT_I_2_we0;
output  [31:0] OUT_I_2_d0;
output  [7:0] OUT_I_2_address1;
output   OUT_I_2_ce1;
output   OUT_I_2_we1;
output  [31:0] OUT_I_2_d1;
output  [7:0] OUT_I_3_address0;
output   OUT_I_3_ce0;
output   OUT_I_3_we0;
output  [31:0] OUT_I_3_d0;
output  [7:0] OUT_I_3_address1;
output   OUT_I_3_ce1;
output   OUT_I_3_we1;
output  [31:0] OUT_I_3_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [8:0] numBF_reg_167;
wire   [8:0] trunc_ln1540_fu_139_p1;
reg   [8:0] trunc_ln1540_reg_173;
wire   [8:0] one_V_fu_143_p2;
reg   [8:0] one_V_reg_178;
wire    ap_CS_fsm_state2;
wire   [3:0] sub3_fu_149_p2;
reg   [3:0] sub3_reg_183;
wire   [3:0] sub5_fu_155_p2;
reg   [3:0] sub5_reg_188;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_ap_start;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_ap_done;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_ap_idle;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_ap_ready;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_ce0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_we0;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_d0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_ce1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_we1;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_d1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_ce0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_we0;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_d0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_ce1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_we1;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_d1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_ce0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_we0;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_d0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_ce1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_we1;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_d1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_ce0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_we0;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_d0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_ce1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_we1;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_d1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_ce0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_we0;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_d0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_ce1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_we1;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_d1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_0_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_0_ce0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_0_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_0_ce1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_1_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_1_ce0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_1_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_1_ce1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_2_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_2_ce0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_2_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_2_ce1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_3_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_3_ce0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_3_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_3_ce1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_0_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_0_ce0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_0_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_0_ce1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_1_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_1_ce0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_1_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_1_ce1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_2_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_2_ce0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_2_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_2_ce1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_3_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_3_ce0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_3_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_3_ce1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_ce0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_we0;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_d0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_ce1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_we1;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_d1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_ce0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_we0;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_d0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_ce1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_we1;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_d1;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_address0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_ce0;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_we0;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_d0;
wire   [7:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_address1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_ce1;
wire    grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_we1;
wire   [31:0] grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_d1;
reg    grp_fft_stages_Pipeline_DFTpts_fu_64_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [9:0] stage_cast_fu_113_p1;
wire   [9:0] DFTpts_fu_117_p2;
wire   [10:0] stage_cast1_fu_109_p1;
wire   [10:0] ec_V_fu_133_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_fft_stages_Pipeline_DFTpts_fu_64_ap_start_reg = 1'b0;
end

fft_fft_stages_Pipeline_DFTpts grp_fft_stages_Pipeline_DFTpts_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_stages_Pipeline_DFTpts_fu_64_ap_start),
    .ap_done(grp_fft_stages_Pipeline_DFTpts_fu_64_ap_done),
    .ap_idle(grp_fft_stages_Pipeline_DFTpts_fu_64_ap_idle),
    .ap_ready(grp_fft_stages_Pipeline_DFTpts_fu_64_ap_ready),
    .zext_ln160(one_V_reg_178),
    .zext_ln157(numBF_reg_167),
    .OUT_I_0_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_address0),
    .OUT_I_0_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_ce0),
    .OUT_I_0_we0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_we0),
    .OUT_I_0_d0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_d0),
    .OUT_I_0_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_address1),
    .OUT_I_0_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_ce1),
    .OUT_I_0_we1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_we1),
    .OUT_I_0_d1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_d1),
    .OUT_R_0_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_address0),
    .OUT_R_0_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_ce0),
    .OUT_R_0_we0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_we0),
    .OUT_R_0_d0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_d0),
    .OUT_R_0_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_address1),
    .OUT_R_0_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_ce1),
    .OUT_R_0_we1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_we1),
    .OUT_R_0_d1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_d1),
    .OUT_R_1_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_address0),
    .OUT_R_1_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_ce0),
    .OUT_R_1_we0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_we0),
    .OUT_R_1_d0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_d0),
    .OUT_R_1_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_address1),
    .OUT_R_1_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_ce1),
    .OUT_R_1_we1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_we1),
    .OUT_R_1_d1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_d1),
    .OUT_R_2_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_address0),
    .OUT_R_2_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_ce0),
    .OUT_R_2_we0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_we0),
    .OUT_R_2_d0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_d0),
    .OUT_R_2_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_address1),
    .OUT_R_2_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_ce1),
    .OUT_R_2_we1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_we1),
    .OUT_R_2_d1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_d1),
    .OUT_R_3_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_address0),
    .OUT_R_3_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_ce0),
    .OUT_R_3_we0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_we0),
    .OUT_R_3_d0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_d0),
    .OUT_R_3_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_address1),
    .OUT_R_3_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_ce1),
    .OUT_R_3_we1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_we1),
    .OUT_R_3_d1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_d1),
    .sub3_cast(sub3_reg_183),
    .sub5_cast(sub5_reg_188),
    .trunc_ln(trunc_ln1540_reg_173),
    .X_R_0_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_0_address0),
    .X_R_0_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_0_ce0),
    .X_R_0_q0(X_R_0_q0),
    .X_R_0_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_0_address1),
    .X_R_0_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_0_ce1),
    .X_R_0_q1(X_R_0_q1),
    .X_R_1_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_1_address0),
    .X_R_1_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_1_ce0),
    .X_R_1_q0(X_R_1_q0),
    .X_R_1_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_1_address1),
    .X_R_1_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_1_ce1),
    .X_R_1_q1(X_R_1_q1),
    .X_R_2_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_2_address0),
    .X_R_2_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_2_ce0),
    .X_R_2_q0(X_R_2_q0),
    .X_R_2_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_2_address1),
    .X_R_2_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_2_ce1),
    .X_R_2_q1(X_R_2_q1),
    .X_R_3_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_3_address0),
    .X_R_3_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_3_ce0),
    .X_R_3_q0(X_R_3_q0),
    .X_R_3_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_3_address1),
    .X_R_3_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_3_ce1),
    .X_R_3_q1(X_R_3_q1),
    .X_I_0_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_0_address0),
    .X_I_0_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_0_ce0),
    .X_I_0_q0(X_I_0_q0),
    .X_I_0_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_0_address1),
    .X_I_0_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_0_ce1),
    .X_I_0_q1(X_I_0_q1),
    .X_I_1_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_1_address0),
    .X_I_1_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_1_ce0),
    .X_I_1_q0(X_I_1_q0),
    .X_I_1_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_1_address1),
    .X_I_1_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_1_ce1),
    .X_I_1_q1(X_I_1_q1),
    .X_I_2_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_2_address0),
    .X_I_2_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_2_ce0),
    .X_I_2_q0(X_I_2_q0),
    .X_I_2_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_2_address1),
    .X_I_2_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_2_ce1),
    .X_I_2_q1(X_I_2_q1),
    .X_I_3_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_3_address0),
    .X_I_3_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_3_ce0),
    .X_I_3_q0(X_I_3_q0),
    .X_I_3_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_3_address1),
    .X_I_3_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_3_ce1),
    .X_I_3_q1(X_I_3_q1),
    .OUT_I_1_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_address0),
    .OUT_I_1_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_ce0),
    .OUT_I_1_we0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_we0),
    .OUT_I_1_d0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_d0),
    .OUT_I_1_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_address1),
    .OUT_I_1_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_ce1),
    .OUT_I_1_we1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_we1),
    .OUT_I_1_d1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_d1),
    .OUT_I_2_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_address0),
    .OUT_I_2_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_ce0),
    .OUT_I_2_we0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_we0),
    .OUT_I_2_d0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_d0),
    .OUT_I_2_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_address1),
    .OUT_I_2_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_ce1),
    .OUT_I_2_we1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_we1),
    .OUT_I_2_d1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_d1),
    .OUT_I_3_address0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_address0),
    .OUT_I_3_ce0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_ce0),
    .OUT_I_3_we0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_we0),
    .OUT_I_3_d0(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_d0),
    .OUT_I_3_address1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_address1),
    .OUT_I_3_ce1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_ce1),
    .OUT_I_3_we1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_we1),
    .OUT_I_3_d1(grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_stages_Pipeline_DFTpts_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_fft_stages_Pipeline_DFTpts_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_fft_stages_Pipeline_DFTpts_fu_64_ap_ready == 1'b1)) begin
            grp_fft_stages_Pipeline_DFTpts_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        numBF_reg_167 <= {{DFTpts_fu_117_p2[9:1]}};
        trunc_ln1540_reg_173 <= trunc_ln1540_fu_139_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        one_V_reg_178 <= one_V_fu_143_p2;
        sub3_reg_183 <= sub3_fu_149_p2;
        sub5_reg_188 <= sub5_fu_155_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_stages_Pipeline_DFTpts_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_fft_stages_Pipeline_DFTpts_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fft_stages_Pipeline_DFTpts_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_fft_stages_Pipeline_DFTpts_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DFTpts_fu_117_p2 = 10'd1 << stage_cast_fu_113_p1;

assign OUT_I_0_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_address0;

assign OUT_I_0_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_address1;

assign OUT_I_0_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_ce0;

assign OUT_I_0_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_ce1;

assign OUT_I_0_d0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_d0;

assign OUT_I_0_d1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_d1;

assign OUT_I_0_we0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_we0;

assign OUT_I_0_we1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_0_we1;

assign OUT_I_1_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_address0;

assign OUT_I_1_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_address1;

assign OUT_I_1_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_ce0;

assign OUT_I_1_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_ce1;

assign OUT_I_1_d0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_d0;

assign OUT_I_1_d1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_d1;

assign OUT_I_1_we0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_we0;

assign OUT_I_1_we1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_1_we1;

assign OUT_I_2_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_address0;

assign OUT_I_2_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_address1;

assign OUT_I_2_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_ce0;

assign OUT_I_2_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_ce1;

assign OUT_I_2_d0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_d0;

assign OUT_I_2_d1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_d1;

assign OUT_I_2_we0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_we0;

assign OUT_I_2_we1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_2_we1;

assign OUT_I_3_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_address0;

assign OUT_I_3_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_address1;

assign OUT_I_3_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_ce0;

assign OUT_I_3_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_ce1;

assign OUT_I_3_d0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_d0;

assign OUT_I_3_d1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_d1;

assign OUT_I_3_we0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_we0;

assign OUT_I_3_we1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_I_3_we1;

assign OUT_R_0_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_address0;

assign OUT_R_0_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_address1;

assign OUT_R_0_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_ce0;

assign OUT_R_0_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_ce1;

assign OUT_R_0_d0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_d0;

assign OUT_R_0_d1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_d1;

assign OUT_R_0_we0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_we0;

assign OUT_R_0_we1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_0_we1;

assign OUT_R_1_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_address0;

assign OUT_R_1_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_address1;

assign OUT_R_1_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_ce0;

assign OUT_R_1_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_ce1;

assign OUT_R_1_d0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_d0;

assign OUT_R_1_d1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_d1;

assign OUT_R_1_we0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_we0;

assign OUT_R_1_we1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_1_we1;

assign OUT_R_2_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_address0;

assign OUT_R_2_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_address1;

assign OUT_R_2_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_ce0;

assign OUT_R_2_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_ce1;

assign OUT_R_2_d0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_d0;

assign OUT_R_2_d1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_d1;

assign OUT_R_2_we0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_we0;

assign OUT_R_2_we1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_2_we1;

assign OUT_R_3_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_address0;

assign OUT_R_3_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_address1;

assign OUT_R_3_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_ce0;

assign OUT_R_3_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_ce1;

assign OUT_R_3_d0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_d0;

assign OUT_R_3_d1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_d1;

assign OUT_R_3_we0 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_we0;

assign OUT_R_3_we1 = grp_fft_stages_Pipeline_DFTpts_fu_64_OUT_R_3_we1;

assign X_I_0_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_0_address0;

assign X_I_0_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_0_address1;

assign X_I_0_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_0_ce0;

assign X_I_0_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_0_ce1;

assign X_I_1_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_1_address0;

assign X_I_1_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_1_address1;

assign X_I_1_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_1_ce0;

assign X_I_1_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_1_ce1;

assign X_I_2_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_2_address0;

assign X_I_2_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_2_address1;

assign X_I_2_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_2_ce0;

assign X_I_2_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_2_ce1;

assign X_I_3_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_3_address0;

assign X_I_3_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_3_address1;

assign X_I_3_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_3_ce0;

assign X_I_3_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_I_3_ce1;

assign X_R_0_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_0_address0;

assign X_R_0_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_0_address1;

assign X_R_0_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_0_ce0;

assign X_R_0_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_0_ce1;

assign X_R_1_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_1_address0;

assign X_R_1_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_1_address1;

assign X_R_1_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_1_ce0;

assign X_R_1_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_1_ce1;

assign X_R_2_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_2_address0;

assign X_R_2_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_2_address1;

assign X_R_2_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_2_ce0;

assign X_R_2_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_2_ce1;

assign X_R_3_address0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_3_address0;

assign X_R_3_address1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_3_address1;

assign X_R_3_ce0 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_3_ce0;

assign X_R_3_ce1 = grp_fft_stages_Pipeline_DFTpts_fu_64_X_R_3_ce1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ec_V_fu_133_p2 = 11'd1024 >> stage_cast1_fu_109_p1;

assign grp_fft_stages_Pipeline_DFTpts_fu_64_ap_start = grp_fft_stages_Pipeline_DFTpts_fu_64_ap_start_reg;

assign one_V_fu_143_p2 = ($signed(numBF_reg_167) + $signed(9'd511));

assign stage_cast1_fu_109_p1 = stage;

assign stage_cast_fu_113_p1 = stage;

assign sub3_fu_149_p2 = ($signed(stage) + $signed(4'd15));

assign sub5_fu_155_p2 = ($signed(stage) + $signed(4'd14));

assign trunc_ln1540_fu_139_p1 = ec_V_fu_133_p2[8:0];

endmodule //fft_fft_stages
