-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_fft_Pipeline_Reverse is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    X_R_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    X_R_ce0 : OUT STD_LOGIC;
    X_R_we0 : OUT STD_LOGIC;
    X_R_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    X_R_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    X_R_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    X_R_ce1 : OUT STD_LOGIC;
    X_R_we1 : OUT STD_LOGIC;
    X_R_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    X_R_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    X_I_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    X_I_ce0 : OUT STD_LOGIC;
    X_I_we0 : OUT STD_LOGIC;
    X_I_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    X_I_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    X_I_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    X_I_ce1 : OUT STD_LOGIC;
    X_I_we1 : OUT STD_LOGIC;
    X_I_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    X_I_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of fft_fft_Pipeline_Reverse is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1024_lc_1 : STD_LOGIC_VECTOR (1023 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv1024_lc_2 : STD_LOGIC_VECTOR (1023 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln69_fu_123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal icmp_ln69_reg_219 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal add_ln69_fu_129_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln69_reg_223 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_s_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_228 : STD_LOGIC_VECTOR (0 downto 0);
    signal X_R_addr_reg_232 : STD_LOGIC_VECTOR (9 downto 0);
    signal X_I_addr_reg_237 : STD_LOGIC_VECTOR (9 downto 0);
    signal X_R_addr_1_reg_242 : STD_LOGIC_VECTOR (9 downto 0);
    signal X_I_addr_1_reg_247 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal i_2_cast_fu_138_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln587_fu_190_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_2_fu_48 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal p_Val2_s_fu_52 : STD_LOGIC_VECTOR (1023 downto 0);
    signal p_Result_2_fu_180_p4 : STD_LOGIC_VECTOR (1023 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln825_fu_144_p1 : STD_LOGIC_VECTOR (1023 downto 0);
    signal shl_ln825_fu_148_p2 : STD_LOGIC_VECTOR (1023 downto 0);
    signal and_ln825_fu_154_p2 : STD_LOGIC_VECTOR (1023 downto 0);
    signal or_ln37_8_fu_166_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln850_fu_176_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0 : BOOLEAN;
    signal ap_predicate_op42_store_state3 : BOOLEAN;
    signal ap_enable_operation_42 : BOOLEAN;
    signal ap_enable_state3_pp0_iter1_stage0 : BOOLEAN;
    signal ap_predicate_op35_load_state2 : BOOLEAN;
    signal ap_enable_operation_35 : BOOLEAN;
    signal ap_enable_state2_pp0_iter0_stage1 : BOOLEAN;
    signal ap_predicate_op41_load_state3 : BOOLEAN;
    signal ap_enable_operation_41 : BOOLEAN;
    signal ap_predicate_op45_store_state3 : BOOLEAN;
    signal ap_enable_operation_45 : BOOLEAN;
    signal ap_predicate_op44_store_state3 : BOOLEAN;
    signal ap_enable_operation_44 : BOOLEAN;
    signal ap_predicate_op37_load_state2 : BOOLEAN;
    signal ap_enable_operation_37 : BOOLEAN;
    signal ap_predicate_op43_load_state3 : BOOLEAN;
    signal ap_enable_operation_43 : BOOLEAN;
    signal ap_predicate_op46_store_state3 : BOOLEAN;
    signal ap_enable_operation_46 : BOOLEAN;
    signal ap_predicate_op30_load_state2 : BOOLEAN;
    signal ap_enable_operation_30 : BOOLEAN;
    signal ap_predicate_op39_load_state3 : BOOLEAN;
    signal ap_enable_operation_39 : BOOLEAN;
    signal ap_predicate_op32_load_state2 : BOOLEAN;
    signal ap_enable_operation_32 : BOOLEAN;
    signal ap_predicate_op40_load_state3 : BOOLEAN;
    signal ap_enable_operation_40 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fft_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    i_2_fu_48_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_2_fu_48 <= ap_const_lv11_0;
                elsif (((icmp_ln69_reg_219 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_2_fu_48 <= add_ln69_reg_223;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_s_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                p_Val2_s_fu_52 <= ap_const_lv1024_lc_1;
            elsif (((p_Result_s_fu_160_p2 = ap_const_lv1_1) and (icmp_ln69_fu_123_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                p_Val2_s_fu_52 <= p_Result_2_fu_180_p4;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((p_Result_s_fu_160_p2 = ap_const_lv1_1) and (icmp_ln69_fu_123_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                X_I_addr_1_reg_247 <= zext_ln587_fu_190_p1(10 - 1 downto 0);
                X_I_addr_reg_237 <= i_2_cast_fu_138_p1(10 - 1 downto 0);
                X_R_addr_1_reg_242 <= zext_ln587_fu_190_p1(10 - 1 downto 0);
                X_R_addr_reg_232 <= i_2_cast_fu_138_p1(10 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln69_reg_223 <= add_ln69_fu_129_p2;
                icmp_ln69_reg_219 <= icmp_ln69_fu_123_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln69_fu_123_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_Result_s_reg_228 <= p_Result_s_fu_160_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;

    X_I_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, X_I_addr_1_reg_247, ap_block_pp0_stage1, zext_ln587_fu_190_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_I_address0 <= X_I_addr_1_reg_247;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            X_I_address0 <= zext_ln587_fu_190_p1(10 - 1 downto 0);
        else 
            X_I_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    X_I_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, X_I_addr_reg_237, i_2_cast_fu_138_p1, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_I_address1 <= X_I_addr_reg_237;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            X_I_address1 <= i_2_cast_fu_138_p1(10 - 1 downto 0);
        else 
            X_I_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    X_I_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            X_I_ce0 <= ap_const_logic_1;
        else 
            X_I_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    X_I_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            X_I_ce1 <= ap_const_logic_1;
        else 
            X_I_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    X_I_d0 <= X_I_q1;
    X_I_d1 <= X_I_q0;

    X_I_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln69_reg_219, p_Result_s_reg_228, ap_block_pp0_stage0_11001)
    begin
        if (((p_Result_s_reg_228 = ap_const_lv1_1) and (icmp_ln69_reg_219 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_I_we0 <= ap_const_logic_1;
        else 
            X_I_we0 <= ap_const_logic_0;
        end if; 
    end process;


    X_I_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln69_reg_219, p_Result_s_reg_228, ap_block_pp0_stage0_11001)
    begin
        if (((p_Result_s_reg_228 = ap_const_lv1_1) and (icmp_ln69_reg_219 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_I_we1 <= ap_const_logic_1;
        else 
            X_I_we1 <= ap_const_logic_0;
        end if; 
    end process;


    X_R_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, X_R_addr_1_reg_242, ap_block_pp0_stage1, zext_ln587_fu_190_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_R_address0 <= X_R_addr_1_reg_242;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            X_R_address0 <= zext_ln587_fu_190_p1(10 - 1 downto 0);
        else 
            X_R_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    X_R_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, X_R_addr_reg_232, i_2_cast_fu_138_p1, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_R_address1 <= X_R_addr_reg_232;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            X_R_address1 <= i_2_cast_fu_138_p1(10 - 1 downto 0);
        else 
            X_R_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    X_R_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            X_R_ce0 <= ap_const_logic_1;
        else 
            X_R_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    X_R_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            X_R_ce1 <= ap_const_logic_1;
        else 
            X_R_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    X_R_d0 <= X_R_q1;
    X_R_d1 <= X_R_q0;

    X_R_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln69_reg_219, p_Result_s_reg_228, ap_block_pp0_stage0_11001)
    begin
        if (((p_Result_s_reg_228 = ap_const_lv1_1) and (icmp_ln69_reg_219 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_R_we0 <= ap_const_logic_1;
        else 
            X_R_we0 <= ap_const_logic_0;
        end if; 
    end process;


    X_R_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln69_reg_219, p_Result_s_reg_228, ap_block_pp0_stage0_11001)
    begin
        if (((p_Result_s_reg_228 = ap_const_lv1_1) and (icmp_ln69_reg_219 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_R_we1 <= ap_const_logic_1;
        else 
            X_R_we1 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln69_fu_129_p2 <= std_logic_vector(unsigned(i_2_fu_48) + unsigned(ap_const_lv11_1));
    and_ln825_fu_154_p2 <= (shl_ln825_fu_148_p2 and p_Val2_s_fu_52);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= (((ap_ST_fsm_pp0_stage1 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage1_subdone)) or ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone)));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln69_fu_123_p2)
    begin
        if (((icmp_ln69_fu_123_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_enable_operation_30_assign_proc : process(ap_predicate_op30_load_state2)
    begin
                ap_enable_operation_30 <= (ap_predicate_op30_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_32_assign_proc : process(ap_predicate_op32_load_state2)
    begin
                ap_enable_operation_32 <= (ap_predicate_op32_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_35_assign_proc : process(ap_predicate_op35_load_state2)
    begin
                ap_enable_operation_35 <= (ap_predicate_op35_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_37_assign_proc : process(ap_predicate_op37_load_state2)
    begin
                ap_enable_operation_37 <= (ap_predicate_op37_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_39_assign_proc : process(ap_predicate_op39_load_state3)
    begin
                ap_enable_operation_39 <= (ap_predicate_op39_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_40_assign_proc : process(ap_predicate_op40_load_state3)
    begin
                ap_enable_operation_40 <= (ap_predicate_op40_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_41_assign_proc : process(ap_predicate_op41_load_state3)
    begin
                ap_enable_operation_41 <= (ap_predicate_op41_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_42_assign_proc : process(ap_predicate_op42_store_state3)
    begin
                ap_enable_operation_42 <= (ap_predicate_op42_store_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_43_assign_proc : process(ap_predicate_op43_load_state3)
    begin
                ap_enable_operation_43 <= (ap_predicate_op43_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_44_assign_proc : process(ap_predicate_op44_store_state3)
    begin
                ap_enable_operation_44 <= (ap_predicate_op44_store_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_45_assign_proc : process(ap_predicate_op45_store_state3)
    begin
                ap_enable_operation_45 <= (ap_predicate_op45_store_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_46_assign_proc : process(ap_predicate_op46_store_state3)
    begin
                ap_enable_operation_46 <= (ap_predicate_op46_store_state3 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_enable_state2_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1)
    begin
                ap_enable_state2_pp0_iter0_stage1 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1));
    end process;


    ap_enable_state3_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state3_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_predicate_op30_load_state2_assign_proc : process(icmp_ln69_fu_123_p2, p_Result_s_fu_160_p2)
    begin
                ap_predicate_op30_load_state2 <= ((p_Result_s_fu_160_p2 = ap_const_lv1_1) and (icmp_ln69_fu_123_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op32_load_state2_assign_proc : process(icmp_ln69_fu_123_p2, p_Result_s_fu_160_p2)
    begin
                ap_predicate_op32_load_state2 <= ((p_Result_s_fu_160_p2 = ap_const_lv1_1) and (icmp_ln69_fu_123_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op35_load_state2_assign_proc : process(icmp_ln69_fu_123_p2, p_Result_s_fu_160_p2)
    begin
                ap_predicate_op35_load_state2 <= ((p_Result_s_fu_160_p2 = ap_const_lv1_1) and (icmp_ln69_fu_123_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op37_load_state2_assign_proc : process(icmp_ln69_fu_123_p2, p_Result_s_fu_160_p2)
    begin
                ap_predicate_op37_load_state2 <= ((p_Result_s_fu_160_p2 = ap_const_lv1_1) and (icmp_ln69_fu_123_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op39_load_state3_assign_proc : process(icmp_ln69_reg_219, p_Result_s_reg_228)
    begin
                ap_predicate_op39_load_state3 <= ((p_Result_s_reg_228 = ap_const_lv1_1) and (icmp_ln69_reg_219 = ap_const_lv1_0));
    end process;


    ap_predicate_op40_load_state3_assign_proc : process(icmp_ln69_reg_219, p_Result_s_reg_228)
    begin
                ap_predicate_op40_load_state3 <= ((p_Result_s_reg_228 = ap_const_lv1_1) and (icmp_ln69_reg_219 = ap_const_lv1_0));
    end process;


    ap_predicate_op41_load_state3_assign_proc : process(icmp_ln69_reg_219, p_Result_s_reg_228)
    begin
                ap_predicate_op41_load_state3 <= ((p_Result_s_reg_228 = ap_const_lv1_1) and (icmp_ln69_reg_219 = ap_const_lv1_0));
    end process;


    ap_predicate_op42_store_state3_assign_proc : process(icmp_ln69_reg_219, p_Result_s_reg_228)
    begin
                ap_predicate_op42_store_state3 <= ((p_Result_s_reg_228 = ap_const_lv1_1) and (icmp_ln69_reg_219 = ap_const_lv1_0));
    end process;


    ap_predicate_op43_load_state3_assign_proc : process(icmp_ln69_reg_219, p_Result_s_reg_228)
    begin
                ap_predicate_op43_load_state3 <= ((p_Result_s_reg_228 = ap_const_lv1_1) and (icmp_ln69_reg_219 = ap_const_lv1_0));
    end process;


    ap_predicate_op44_store_state3_assign_proc : process(icmp_ln69_reg_219, p_Result_s_reg_228)
    begin
                ap_predicate_op44_store_state3 <= ((p_Result_s_reg_228 = ap_const_lv1_1) and (icmp_ln69_reg_219 = ap_const_lv1_0));
    end process;


    ap_predicate_op45_store_state3_assign_proc : process(icmp_ln69_reg_219, p_Result_s_reg_228)
    begin
                ap_predicate_op45_store_state3 <= ((p_Result_s_reg_228 = ap_const_lv1_1) and (icmp_ln69_reg_219 = ap_const_lv1_0));
    end process;


    ap_predicate_op46_store_state3_assign_proc : process(icmp_ln69_reg_219, p_Result_s_reg_228)
    begin
                ap_predicate_op46_store_state3 <= ((p_Result_s_reg_228 = ap_const_lv1_1) and (icmp_ln69_reg_219 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    i_2_cast_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_2_fu_48),64));
    icmp_ln69_fu_123_p2 <= "1" when (i_2_fu_48 = ap_const_lv11_400) else "0";
    
    or_ln37_8_fu_166_p4_proc : process(i_2_fu_48)
    variable vlo_cpy : STD_LOGIC_VECTOR(11+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(11+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(11 - 1 downto 0);
    variable or_ln37_8_fu_166_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(11 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(11 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(11 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(4 - 1 downto 0) := ap_const_lv32_9(4 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(4 - 1 downto 0) := ap_const_lv32_0(4 - 1 downto 0);
        v0_cpy := i_2_fu_48;
        if (vlo_cpy(4 - 1 downto 0) > vhi_cpy(4 - 1 downto 0)) then
            vhi_cpy(4-1 downto 0) := std_logic_vector(11-1-unsigned(ap_const_lv32_0(4-1 downto 0)));
            vlo_cpy(4-1 downto 0) := std_logic_vector(11-1-unsigned(ap_const_lv32_9(4-1 downto 0)));
            for or_ln37_8_fu_166_p4_i in 0 to 11-1 loop
                v0_cpy(or_ln37_8_fu_166_p4_i) := i_2_fu_48(11-1-or_ln37_8_fu_166_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(4-1 downto 0)))));

        section := (others=>'0');
        section(4-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(4-1 downto 0)) - unsigned(vlo_cpy(4-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(11-1 downto 0)))));
        res_mask := res_mask(11-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        or_ln37_8_fu_166_p4 <= resvalue(10-1 downto 0);
    end process;

    
    p_Result_2_fu_180_p4_proc : process(p_Val2_s_fu_52, zext_ln850_fu_176_p1)
    begin
        p_Result_2_fu_180_p4 <= p_Val2_s_fu_52;
        if to_integer(unsigned(zext_ln850_fu_176_p1)) >= p_Val2_s_fu_52'low and to_integer(unsigned(zext_ln850_fu_176_p1)) <= p_Val2_s_fu_52'high then
            p_Result_2_fu_180_p4(to_integer(unsigned(zext_ln850_fu_176_p1))) <= ap_const_lv1_1(0);
        end if;
    end process;

    p_Result_s_fu_160_p2 <= "1" when (and_ln825_fu_154_p2 = ap_const_lv1024_lc_1) else "0";
    shl_ln825_fu_148_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv1024_lc_2),to_integer(unsigned('0' & zext_ln825_fu_144_p1(31-1 downto 0)))));
    zext_ln587_fu_190_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln37_8_fu_166_p4),64));
    zext_ln825_fu_144_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_2_fu_48),1024));
    zext_ln850_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln37_8_fu_166_p4),32));
end behav;
